version: "3.7"
services:
  mssql-server:
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: $SA_PASSWORD
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    healthcheck:
      test:
        - "CMD"
        - /bin/sh
        - '-c'
        - 'ln -sfn /opt/mssql-tools/bin/sqlcmd /usr/bin/sqlcmd'
        - '/opt/mssql-tools/bin/sqlcmd -U sa -P "${SA_PASSWORD}" -Q "SELECT \"READY\"" | grep -q "READY"'
      interval: 5s
      retries: 10
    volumes:
      - sql_data_volume:/var/opt/mssql
  api:
    build:
      context: .
    ports:
      - "5000:80"
    environment:
      DbServer: "mssql-server"
      DbPort: "1433"
      DbUser: "SA"
      Password: "DockerTest123"
      Database: "kanban"
    depends_on:
      mssql-server:
        condition: service_healthy
volumes: 
  sql_data_volume: